name: Bug report
about: Create a bug report
title: "[Bug]: "
labels: bug
assignees: 
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
